server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LoginService
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: LOGIN-SERVICE
